x-airflow-common: &airflow-common
    image: apache/airflow:2.10.0

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      MONGO_URI: ${MONGO_URI}
      AIRFLOW_ADMIN_USERNAME: ${AIRFLOW_ADMIN_USERNAME}
      AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
      AIRFLOW_ADMIN_FIRSTNAME: ${AIRFLOW_ADMIN_FIRSTNAME}
      AIRFLOW_ADMIN_LASTNAME: ${AIRFLOW_ADMIN_LASTNAME}
      AIRFLOW_ADMIN_EMAIL: ${AIRFLOW_ADMIN_EMAIL}

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./ETL:/opt/airflow/ETL
      - ./data:/data

    networks:
      - cyberlab_net

    depends_on:
      postgres:
        condition: service_healthy
        
services:

  attacker:
    container_name: attacker-lab

    build:
      context: ./attacker
      dockerfile: Dockerfile

    working_dir: /app

    volumes:
      - ./attacker:/app

    networks:
      - cyberlab_net

    stdin_open: true
    tty: true

    restart: unless-stopped

    command: tail -f /dev/null

  backend:
    container_name: backend-lab

    build:
      context: ./backend
      dockerfile: Dockerfile

    volumes:
      - ./data:/data

    networks:
      - cyberlab_net

    ports:
      - "8000:8000"

    restart: unless-stopped

  monitor :
    container_name: monitor-lab

    build:
      context: ./monitor
      dockerfile: Dockerfile

    volumes:
      - ./monitor/captures:/captures

    networks:
      - cyberlab_net
    
    cap_add:
      - NET_ADMIN
      - NET_RAW

    restart: unless-stopped

  etl:
    container_name: etl-lab

    build:
      context: ./ETL
      dockerfile: Dockerfile

    volumes:
      - ./data:/data

    networks:
      - cyberlab_net
    
  mongodb:
    container_name: mongodb-lab

    image: mongo:latest

    volumes:
      - mongodb_data:/data/db

    networks:
      - cyberlab_net

    ports:
      - "27017:27017"

    restart: unless-stopped

  postgres:
    image: postgres:15

    container_name: postgres-airflow

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
    - postgres_data:/var/lib/postgresql/data

    networks:
    - cyberlab_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  airflow-scheduler:
    <<: *airflow-common

    container_name: airflow-scheduler

    command: scheduler

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    restart: unless-stopped
  airflow-webserver:
    <<: *airflow-common

    container_name: airflow-webserver

    command: webserver

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    ports:
      - "8080:8080"

    restart: unless-stopped
  airflow-init:
    <<: *airflow-common

    container_name: airflow-init

    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate

        if ! airflow users list | grep -q "$AIRFLOW_ADMIN_USERNAME"; then
          airflow users create \
            --username "$AIRFLOW_ADMIN_USERNAME" \
            --firstname "$AIRFLOW_ADMIN_FIRSTNAME" \
            --lastname "$AIRFLOW_ADMIN_LASTNAME" \
            --role Admin \
            --email "$AIRFLOW_ADMIN_EMAIL" \
            --password "$AIRFLOW_ADMIN_PASSWORD"
        else
          echo "Airflow admin user already exists."
        fi
    restart: "no" 
volumes:
    mongodb_data:
    postgres_data:

networks:
  cyberlab_net:
    driver: bridge