services:

  attacker:
    container_name: attacker-lab

    build:
      context: ./attacker
      dockerfile: Dockerfile

    working_dir: /app

    volumes:
      - ./attacker:/app

    networks:
      - cyberlab_net

    stdin_open: true
    tty: true

    restart: unless-stopped

    command: tail -f /dev/null

  backend:
    container_name: backend-lab

    build:
      context: ./backend
      dockerfile: Dockerfile

    volumes:
      - ./data:/data

    networks:
      - cyberlab_net

    ports:
      - "8000:8000"

    restart: unless-stopped

  monitor :
    container_name: monitor-lab

    build:
      context: ./monitor
      dockerfile: Dockerfile

    volumes:
      - ./monitor/captures:/captures

    networks:
      - cyberlab_net
    
    cap_add:
      - NET_ADMIN
      - NET_RAW

    restart: unless-stopped

  etl:
    container_name: etl-lab

    build:
      context: ./ETL
      dockerfile: Dockerfile

    volumes:
      - ./data:/data

    networks:
      - cyberlab_net
    
  MongoDB:
    container_name: mongodb-lab

    image: mongo:latest

    volumes:
      - mongodb_data:/data/db

    networks:
      - cyberlab_net

    ports:
      - "27017:27017"

    restart: unless-stopped
volumes:
    mongodb_data:

networks:
  cyberlab_net:
    driver: bridge